; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = serial
# upload_port = /dev/ttyUSB0      ; ปล่อยให้ PlatformIO หาเอง หรือใส่ /dev/ttyUSB0
# monitor_port = /dev/ttyUSB0
monitor_speed = 115200
src_filter = +<*> -<Ultrasonic.cpp> -<mpu_test.cpp>

lib_deps =
    adafruit/Adafruit BNO055 @ ^1.6.3
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.16.1
    wollewald/INA226_WE @ ^1.2.9